package ba.unsa.etf.si.app.entity;
// Generated May 10, 2015 4:50:37 PM by Hibernate Tools 4.3.1



/**
 * Parametri generated by hbm2java
 */
public class Parametri  implements java.io.Serializable {


     private int id;
     private Double cijenaVodePoKubiku;
     private Double cijenaKanalizacijePoKubiku;
     private Double pvnZaKoristenjeVoda;
     private Double pvnZaZastituVoda;
     private Double fiksniVodaZaPausalce;
     private Double fiksniKanalizacijaZaPausalce;
     private Double fiksnaCijena;
     private Double stopaPdv;

    public Parametri() {
    }

	
    public Parametri(int id) {
        this.id = id;
    }
    public Parametri(int id, Double cijenaVodePoKubiku, Double cijenaKanalizacijePoKubiku, Double pvnZaKoristenjeVoda, Double pvnZaZastituVoda, Double fiksniVodaZaPausalce, Double fiksniKanalizacijaZaPausalce, Double fiksnaCijena, Double stopaPdv) {
       this.id = id;
       this.cijenaVodePoKubiku = cijenaVodePoKubiku;
       this.cijenaKanalizacijePoKubiku = cijenaKanalizacijePoKubiku;
       this.pvnZaKoristenjeVoda = pvnZaKoristenjeVoda;
       this.pvnZaZastituVoda = pvnZaZastituVoda;
       this.fiksniVodaZaPausalce = fiksniVodaZaPausalce;
       this.fiksniKanalizacijaZaPausalce = fiksniKanalizacijaZaPausalce;
       this.fiksnaCijena = fiksnaCijena;
       this.stopaPdv = stopaPdv;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Double getCijenaVodePoKubiku() {
        return this.cijenaVodePoKubiku;
    }
    
    public void setCijenaVodePoKubiku(Double cijenaVodePoKubiku) {
        this.cijenaVodePoKubiku = cijenaVodePoKubiku;
    }
    public Double getCijenaKanalizacijePoKubiku() {
        return this.cijenaKanalizacijePoKubiku;
    }
    
    public void setCijenaKanalizacijePoKubiku(Double cijenaKanalizacijePoKubiku) {
        this.cijenaKanalizacijePoKubiku = cijenaKanalizacijePoKubiku;
    }
    public Double getPvnZaKoristenjeVoda() {
        return this.pvnZaKoristenjeVoda;
    }
    
    public void setPvnZaKoristenjeVoda(Double pvnZaKoristenjeVoda) {
        this.pvnZaKoristenjeVoda = pvnZaKoristenjeVoda;
    }
    public Double getPvnZaZastituVoda() {
        return this.pvnZaZastituVoda;
    }
    
    public void setPvnZaZastituVoda(Double pvnZaZastituVoda) {
        this.pvnZaZastituVoda = pvnZaZastituVoda;
    }
    public Double getFiksniVodaZaPausalce() {
        return this.fiksniVodaZaPausalce;
    }
    
    public void setFiksniVodaZaPausalce(Double fiksniVodaZaPausalce) {
        this.fiksniVodaZaPausalce = fiksniVodaZaPausalce;
    }
    public Double getFiksniKanalizacijaZaPausalce() {
        return this.fiksniKanalizacijaZaPausalce;
    }
    
    public void setFiksniKanalizacijaZaPausalce(Double fiksniKanalizacijaZaPausalce) {
        this.fiksniKanalizacijaZaPausalce = fiksniKanalizacijaZaPausalce;
    }
    public Double getFiksnaCijena() {
        return this.fiksnaCijena;
    }
    
    public void setFiksnaCijena(Double fiksnaCijena) {
        this.fiksnaCijena = fiksnaCijena;
    }
    public Double getStopaPdv() {
        return this.stopaPdv;
    }
    
    public void setStopaPdv(Double stopaPdv) {
        this.stopaPdv = stopaPdv;
    }




}


