/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ba.etf.unsa.si.app.ui;

import ba.unsa.etf.si.app.entity.Parametri;
import ba.unsa.etf.si.app.services.ParametriService;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.JOptionPane;


/**
 *
 * @author Azra
 */
public class Home extends javax.swing.JFrame {
    GridBagLayout layout = new GridBagLayout();
    PotrosacPanel1 p1;
    PotrosacPanel2 p2;
    PotrosacPanel3 p3;
    PotrosacPanel4 p4;
    ParametriPanel1 m1;
    ParametriPanel2 m2;
    RacuniPanel1 r1;
    RacuniPanel2 r2;
    IzvjestajPanel1 i1;
    IzvjestajPanel2 i2;
    OcitanjaPanel1 o1;
    OcitanjaPanel2 o2;
    OcitanjaPanel3 o3;
    KorisniciPanel1 k1;
    KorisniciPanel2 k2;
    KorisniciPanel3 k3;
    KorisniciPanel4 k4;
    Boolean Admin;
    ParametriService servis;
    Parametri parametri;
    /**
     * Creates new form Home
     * @param adminTest
     */
    public Home(Boolean adminTest) {
        initComponents();
        // Admin Test
        Admin = adminTest;
        //bijela pozadina
        Container container = this.getContentPane();
        container.setBackground(Color.white); 
        //na pocetku je vidljiv potrosaciPanel, ostali su na false
        parametriPanel.setVisible(false);
        racuniPanel.setVisible(false);
        izvjestajPanel.setVisible(false);
        ocitanjaPanel.setVisible(false);
        korisniciPanel.setVisible(false);
        //instance svih panela u formi
        p1 = new PotrosacPanel1();
        p2 = new PotrosacPanel2();
        p3 = new PotrosacPanel3();
        p4 = new PotrosacPanel4();
        m1 = new ParametriPanel1();
        m2 = new ParametriPanel2();
        r1 = new RacuniPanel1();
        r2 = new RacuniPanel2();
        i1 = new IzvjestajPanel1();
        i2 = new IzvjestajPanel2();
        o1 = new OcitanjaPanel1();
        o2 = new OcitanjaPanel2();
        o3 = new OcitanjaPanel3();
        k1 = new KorisniciPanel1();
        k2 = new KorisniciPanel2();
        k3 = new KorisniciPanel3();
        k4 = new KorisniciPanel4();
        potrosaciDinamicki.setLayout(layout);
        parametriDinamicki.setLayout(layout);
        racuniDinamicki.setLayout(layout);
        izvjestajDinamicki.setLayout(layout);
        ocitanjaDinamicki.setLayout(layout);
        korisniciDinamicki.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        potrosaciDinamicki.add(p1,c);
        c.gridx = 0;
        c.gridy = 0;
        potrosaciDinamicki.add(p2,c);
        c.gridx = 0;
        c.gridy = 0;
        potrosaciDinamicki.add(p3,c);
        c.gridx = 0;
        c.gridy = 0;
        potrosaciDinamicki.add(p4,c);
        c.gridx = 0;
        c.gridy = 0;
        parametriDinamicki.add(m1,c);
        c.gridx = 0;
        c.gridy = 0;
        parametriDinamicki.add(m2,c);
        c.gridx = 0;
        c.gridy = 0;
        racuniDinamicki.add(r1,c);
        c.gridx = 0;
        c.gridy = 0;
        racuniDinamicki.add(r2,c);
        c.gridx = 0;
        c.gridy = 0;
        izvjestajDinamicki.add(i1,c);
        c.gridx = 0;
        c.gridy = 0;
        izvjestajDinamicki.add(i2,c);
        c.gridx = 0;
        c.gridy = 0;
        ocitanjaDinamicki.add(o1,c);
        c.gridx = 0;
        c.gridy = 0;
        ocitanjaDinamicki.add(o2,c);
        c.gridx = 0;
        c.gridy = 0;
        ocitanjaDinamicki.add(o3,c);
        c.gridx = 0;
        c.gridy = 0;
        korisniciDinamicki.add(k1,c);
        c.gridx = 0;
        c.gridy = 0;
        korisniciDinamicki.add(k2,c);
        c.gridx = 0;
        c.gridy = 0;
        korisniciDinamicki.add(k3,c);
        c.gridx = 0;
        c.gridy = 0;
        korisniciDinamicki.add(k4,c);
        //prvi panel Potrosaci vidljiv, ostali sakriveni
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jXHeader2 = new org.jdesktop.swingx.JXHeader();
        slojevi = new javax.swing.JLayeredPane();
        potrosaciPanel = new javax.swing.JPanel();
        potrosaciOpcije = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        potrosaciDinamicki = new javax.swing.JPanel();
        parametriPanel = new javax.swing.JPanel();
        parametriOpcije = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        parametriDinamicki = new javax.swing.JPanel();
        racuniPanel = new javax.swing.JPanel();
        racuniOpcije = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        racuniDinamicki = new javax.swing.JPanel();
        izvjestajPanel = new javax.swing.JPanel();
        izvjestajOpcije = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        izvjestajDinamicki = new javax.swing.JPanel();
        ocitanjaPanel = new javax.swing.JPanel();
        ocitanjaOpcije = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        ocitanjaDinamicki = new javax.swing.JPanel();
        korisniciPanel = new javax.swing.JPanel();
        korisniciDinamicki = new javax.swing.JPanel();
        korisniciOpcije = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        potrosaciMenu = new javax.swing.JMenu();
        parametriMenu = new javax.swing.JMenu();
        racuniMenu = new javax.swing.JMenu();
        izvjestajMenu = new javax.swing.JMenu();
        ocitanjaMenu = new javax.swing.JMenu();
        korisniciMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        slojevi.setBackground(new java.awt.Color(255, 255, 255));

        potrosaciPanel.setBackground(new java.awt.Color(255, 255, 255));

        potrosaciOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("KREIRAJ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 153));
        jButton2.setText("IZMIJENI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 102, 153));
        jButton3.setText("IZBRIŠI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 102, 153));
        jButton4.setText("PRETRAŽI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout potrosaciOpcijeLayout = new javax.swing.GroupLayout(potrosaciOpcije);
        potrosaciOpcije.setLayout(potrosaciOpcijeLayout);
        potrosaciOpcijeLayout.setHorizontalGroup(
            potrosaciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potrosaciOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(potrosaciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );
        potrosaciOpcijeLayout.setVerticalGroup(
            potrosaciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potrosaciOpcijeLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        potrosaciDinamicki.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout potrosaciDinamickiLayout = new javax.swing.GroupLayout(potrosaciDinamicki);
        potrosaciDinamicki.setLayout(potrosaciDinamickiLayout);
        potrosaciDinamickiLayout.setHorizontalGroup(
            potrosaciDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        potrosaciDinamickiLayout.setVerticalGroup(
            potrosaciDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout potrosaciPanelLayout = new javax.swing.GroupLayout(potrosaciPanel);
        potrosaciPanel.setLayout(potrosaciPanelLayout);
        potrosaciPanelLayout.setHorizontalGroup(
            potrosaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(potrosaciPanelLayout.createSequentialGroup()
                .addComponent(potrosaciOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(potrosaciDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        potrosaciPanelLayout.setVerticalGroup(
            potrosaciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(potrosaciOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(potrosaciDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        parametriPanel.setBackground(new java.awt.Color(255, 255, 255));
        parametriPanel.setPreferredSize(new java.awt.Dimension(785, 449));

        parametriOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 153));
        jButton5.setText("PREGLEDAJ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 102, 153));
        jButton6.setText("IZMIJENI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout parametriOpcijeLayout = new javax.swing.GroupLayout(parametriOpcije);
        parametriOpcije.setLayout(parametriOpcijeLayout);
        parametriOpcijeLayout.setHorizontalGroup(
            parametriOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametriOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(parametriOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        parametriOpcijeLayout.setVerticalGroup(
            parametriOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametriOpcijeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        parametriDinamicki.setBackground(new java.awt.Color(255, 255, 255));
        parametriDinamicki.setPreferredSize(new java.awt.Dimension(643, 449));

        javax.swing.GroupLayout parametriDinamickiLayout = new javax.swing.GroupLayout(parametriDinamicki);
        parametriDinamicki.setLayout(parametriDinamickiLayout);
        parametriDinamickiLayout.setHorizontalGroup(
            parametriDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        parametriDinamickiLayout.setVerticalGroup(
            parametriDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout parametriPanelLayout = new javax.swing.GroupLayout(parametriPanel);
        parametriPanel.setLayout(parametriPanelLayout);
        parametriPanelLayout.setHorizontalGroup(
            parametriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(parametriPanelLayout.createSequentialGroup()
                .addComponent(parametriOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parametriDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, 653, Short.MAX_VALUE))
        );
        parametriPanelLayout.setVerticalGroup(
            parametriPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(parametriOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parametriDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        racuniPanel.setBackground(new java.awt.Color(255, 255, 255));

        racuniOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton8.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(0, 102, 153));
        jButton8.setText("PRETRAŽI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(0, 102, 153));
        jButton9.setText("GENERIŠI");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout racuniOpcijeLayout = new javax.swing.GroupLayout(racuniOpcije);
        racuniOpcije.setLayout(racuniOpcijeLayout);
        racuniOpcijeLayout.setHorizontalGroup(
            racuniOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(racuniOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(racuniOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        racuniOpcijeLayout.setVerticalGroup(
            racuniOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(racuniOpcijeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton8)
                .addGap(18, 18, 18)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        racuniDinamicki.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout racuniDinamickiLayout = new javax.swing.GroupLayout(racuniDinamicki);
        racuniDinamicki.setLayout(racuniDinamickiLayout);
        racuniDinamickiLayout.setHorizontalGroup(
            racuniDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        racuniDinamickiLayout.setVerticalGroup(
            racuniDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout racuniPanelLayout = new javax.swing.GroupLayout(racuniPanel);
        racuniPanel.setLayout(racuniPanelLayout);
        racuniPanelLayout.setHorizontalGroup(
            racuniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(racuniPanelLayout.createSequentialGroup()
                .addComponent(racuniOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(racuniDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        racuniPanelLayout.setVerticalGroup(
            racuniPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(racuniOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(racuniDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        izvjestajPanel.setBackground(new java.awt.Color(255, 255, 255));
        izvjestajPanel.setPreferredSize(new java.awt.Dimension(785, 449));

        izvjestajOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton10.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton10.setForeground(new java.awt.Color(0, 102, 153));
        jButton10.setText("KREIRAJ");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton11.setForeground(new java.awt.Color(0, 102, 153));
        jButton11.setText("PREGLEDAJ");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout izvjestajOpcijeLayout = new javax.swing.GroupLayout(izvjestajOpcije);
        izvjestajOpcije.setLayout(izvjestajOpcijeLayout);
        izvjestajOpcijeLayout.setHorizontalGroup(
            izvjestajOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izvjestajOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(izvjestajOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );
        izvjestajOpcijeLayout.setVerticalGroup(
            izvjestajOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izvjestajOpcijeLayout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jButton10)
                .addGap(18, 18, 18)
                .addComponent(jButton11)
                .addContainerGap(191, Short.MAX_VALUE))
        );

        izvjestajDinamicki.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout izvjestajDinamickiLayout = new javax.swing.GroupLayout(izvjestajDinamicki);
        izvjestajDinamicki.setLayout(izvjestajDinamickiLayout);
        izvjestajDinamickiLayout.setHorizontalGroup(
            izvjestajDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        izvjestajDinamickiLayout.setVerticalGroup(
            izvjestajDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout izvjestajPanelLayout = new javax.swing.GroupLayout(izvjestajPanel);
        izvjestajPanel.setLayout(izvjestajPanelLayout);
        izvjestajPanelLayout.setHorizontalGroup(
            izvjestajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(izvjestajPanelLayout.createSequentialGroup()
                .addComponent(izvjestajOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(izvjestajDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        izvjestajPanelLayout.setVerticalGroup(
            izvjestajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(izvjestajOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(izvjestajPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(izvjestajDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ocitanjaPanel.setBackground(new java.awt.Color(255, 255, 255));

        ocitanjaOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(0, 102, 153));
        jButton7.setText("UNESI");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton12.setForeground(new java.awt.Color(0, 102, 153));
        jButton12.setText("IZMIJENI");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton13.setForeground(new java.awt.Color(0, 102, 153));
        jButton13.setText("IZBRIŠI");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ocitanjaOpcijeLayout = new javax.swing.GroupLayout(ocitanjaOpcije);
        ocitanjaOpcije.setLayout(ocitanjaOpcijeLayout);
        ocitanjaOpcijeLayout.setHorizontalGroup(
            ocitanjaOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ocitanjaOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ocitanjaOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ocitanjaOpcijeLayout.setVerticalGroup(
            ocitanjaOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ocitanjaOpcijeLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jButton7)
                .addGap(18, 18, 18)
                .addComponent(jButton12)
                .addGap(18, 18, 18)
                .addComponent(jButton13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ocitanjaDinamicki.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ocitanjaDinamickiLayout = new javax.swing.GroupLayout(ocitanjaDinamicki);
        ocitanjaDinamicki.setLayout(ocitanjaDinamickiLayout);
        ocitanjaDinamickiLayout.setHorizontalGroup(
            ocitanjaDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 643, Short.MAX_VALUE)
        );
        ocitanjaDinamickiLayout.setVerticalGroup(
            ocitanjaDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ocitanjaPanelLayout = new javax.swing.GroupLayout(ocitanjaPanel);
        ocitanjaPanel.setLayout(ocitanjaPanelLayout);
        ocitanjaPanelLayout.setHorizontalGroup(
            ocitanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ocitanjaPanelLayout.createSequentialGroup()
                .addComponent(ocitanjaOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ocitanjaDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ocitanjaPanelLayout.setVerticalGroup(
            ocitanjaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ocitanjaOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ocitanjaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ocitanjaDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        korisniciPanel.setBackground(new java.awt.Color(255, 255, 255));

        korisniciDinamicki.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout korisniciDinamickiLayout = new javax.swing.GroupLayout(korisniciDinamicki);
        korisniciDinamicki.setLayout(korisniciDinamickiLayout);
        korisniciDinamickiLayout.setHorizontalGroup(
            korisniciDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );
        korisniciDinamickiLayout.setVerticalGroup(
            korisniciDinamickiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        korisniciOpcije.setBackground(new java.awt.Color(0, 102, 153));

        jButton14.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton14.setForeground(new java.awt.Color(0, 102, 153));
        jButton14.setText("KREIRAJ");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton15.setForeground(new java.awt.Color(0, 102, 153));
        jButton15.setText("IZMIJENI");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton16.setForeground(new java.awt.Color(0, 102, 153));
        jButton16.setText("IZBRIŠI");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton17.setForeground(new java.awt.Color(0, 102, 153));
        jButton17.setText("PRETRAŽI");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout korisniciOpcijeLayout = new javax.swing.GroupLayout(korisniciOpcije);
        korisniciOpcije.setLayout(korisniciOpcijeLayout);
        korisniciOpcijeLayout.setHorizontalGroup(
            korisniciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(korisniciOpcijeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(korisniciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
        );
        korisniciOpcijeLayout.setVerticalGroup(
            korisniciOpcijeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(korisniciOpcijeLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButton14)
                .addGap(18, 18, 18)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jButton16)
                .addGap(18, 18, 18)
                .addComponent(jButton17)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout korisniciPanelLayout = new javax.swing.GroupLayout(korisniciPanel);
        korisniciPanel.setLayout(korisniciPanelLayout);
        korisniciPanelLayout.setHorizontalGroup(
            korisniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(korisniciPanelLayout.createSequentialGroup()
                .addComponent(korisniciOpcije, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(korisniciDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        korisniciPanelLayout.setVerticalGroup(
            korisniciPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(korisniciOpcije, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(korisniciDinamicki, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout slojeviLayout = new javax.swing.GroupLayout(slojevi);
        slojevi.setLayout(slojeviLayout);
        slojeviLayout.setHorizontalGroup(
            slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(potrosaciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(parametriPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(racuniPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(izvjestajPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ocitanjaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(korisniciPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        slojeviLayout.setVerticalGroup(
            slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(potrosaciPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(parametriPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(racuniPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(izvjestajPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ocitanjaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(slojeviLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(korisniciPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        slojevi.setLayer(potrosaciPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slojevi.setLayer(parametriPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slojevi.setLayer(racuniPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slojevi.setLayer(izvjestajPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slojevi.setLayer(ocitanjaPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        slojevi.setLayer(korisniciPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        potrosaciMenu.setText("Potrošači");
        potrosaciMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                potrosaciMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(potrosaciMenu);

        parametriMenu.setText("Parametri za obračun");
        parametriMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                parametriMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(parametriMenu);

        racuniMenu.setText("Računi");
        racuniMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                racuniMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(racuniMenu);

        izvjestajMenu.setText("Izvještaj");
        izvjestajMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                izvjestajMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(izvjestajMenu);

        ocitanjaMenu.setText("Očitanja");
        ocitanjaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ocitanjaMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(ocitanjaMenu);

        korisniciMenu.setText("Korisnici");
        korisniciMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                korisniciMenuMouseClicked(evt);
            }
        });
        jMenuBar2.add(korisniciMenu);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXHeader2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(slojevi)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(slojevi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXHeader2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void potrosaciMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_potrosaciMenuMouseClicked
        potrosaciPanel.setVisible(true);
        parametriPanel.setVisible(false);
        racuniPanel.setVisible(false);
        izvjestajPanel.setVisible(false);
        ocitanjaPanel.setVisible(false);
        korisniciPanel.setVisible(false);
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_potrosaciMenuMouseClicked

    private void parametriMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_parametriMenuMouseClicked
        potrosaciPanel.setVisible(false);
        parametriPanel.setVisible(true);
        racuniPanel.setVisible(false);
        izvjestajPanel.setVisible(false);
        ocitanjaPanel.setVisible(false);
        korisniciPanel.setVisible(false);
        m1.setVisible(true);
        m2.setVisible(false);
// TODO add yourhandling code here:
    }//GEN-LAST:event_parametriMenuMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        m1.setVisible(true);
        m2.setVisible(false);
        
          //parametri za obracun, uzeti iz baze, postavljeni u text fields
        servis = new ParametriService();
        parametri = new Parametri();
        try{
            parametri = servis.dajParametre();
            m1.setVodaText(parametri.getCijenaVodePoKubiku());
            m1.setKanText(parametri.getCijenaKanalizacijePoKubiku());
            m1.setFiksnoText(parametri.getFiksnaCijena());
            m1.setKubiciVoda(parametri.getFiksniVodaZaPausalce());
            m1.setKubiciKan(parametri.getFiksniKanalizacijaZaPausalce());
            m1.setPVN1(parametri.getPvnZaKoristenjeVoda());
            m1.setPVN2(parametri.getPvnZaZastituVoda());
            m1.setPDV(parametri.getStopaPdv());
        }
        catch(Exception e){
            //"niste postavili parametre" poruka
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        m1.setVisible(false);
        m2.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void racuniMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_racuniMenuMouseClicked
        potrosaciPanel.setVisible(false);
        parametriPanel.setVisible(false);
        racuniPanel.setVisible(true);
        izvjestajPanel.setVisible(false);
        ocitanjaPanel.setVisible(false);
        korisniciPanel.setVisible(false);
        r1.setVisible(true);
        r2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_racuniMenuMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        r1.setVisible(false);
        r2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed

        r1.setVisible(true);
        r2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        i1.setVisible(true);
        i2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        i1.setVisible(false);
        i2.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void izvjestajMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_izvjestajMenuMouseClicked
        potrosaciPanel.setVisible(false);
        parametriPanel.setVisible(false);
        racuniPanel.setVisible(false);
        izvjestajPanel.setVisible(true);
        ocitanjaPanel.setVisible(false);
        korisniciPanel.setVisible(false);
        i1.setVisible(true);
        i2.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_izvjestajMenuMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        p4.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        p1.setVisible(false);
        p2.setVisible(true);
        p3.setVisible(false);
        p4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        p1.setVisible(true);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(false);
        p4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ocitanjaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ocitanjaMenuMouseClicked
        potrosaciPanel.setVisible(false);
        parametriPanel.setVisible(false);
        racuniPanel.setVisible(false);
        izvjestajPanel.setVisible(false);
        ocitanjaPanel.setVisible(true);
        korisniciPanel.setVisible(false);
        o1.setVisible(true);
        o2.setVisible(false);
        o3.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ocitanjaMenuMouseClicked

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        o1.setVisible(false);
        o2.setVisible(true);
        o3.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
    
        o1.setVisible(false);
        o2.setVisible(false);
        o3.setVisible(true);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        
        o1.setVisible(true);
        o2.setVisible(false);
        o3.setVisible(false);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        
        k1.setVisible(true);
        k2.setVisible(false);
        k3.setVisible(false);
        k4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        
        k1.setVisible(false);
        k2.setVisible(true);
        k3.setVisible(false);
        k4.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        
        k1.setVisible(false);
        k2.setVisible(false);
        k3.setVisible(true);
        k4.setVisible(false);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        
        k1.setVisible(false);
        k2.setVisible(false);
        k3.setVisible(false);
        k4.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void korisniciMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_korisniciMenuMouseClicked
        if(Admin){
            potrosaciPanel.setVisible(false);
            parametriPanel.setVisible(false);
            racuniPanel.setVisible(false);
            izvjestajPanel.setVisible(false);
            ocitanjaPanel.setVisible(false);
            korisniciPanel.setVisible(true);
            k1.setVisible(true);
            k2.setVisible(false);
            k3.setVisible(false);
            k4.setVisible(false);
        }
        else{
            JOptionPane.showMessageDialog(null, "Niste Administrator!");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_korisniciMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home(false).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel izvjestajDinamicki;
    private javax.swing.JMenu izvjestajMenu;
    private javax.swing.JPanel izvjestajOpcije;
    private javax.swing.JPanel izvjestajPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JMenuBar jMenuBar2;
    private org.jdesktop.swingx.JXHeader jXHeader2;
    private javax.swing.JPanel korisniciDinamicki;
    private javax.swing.JMenu korisniciMenu;
    private javax.swing.JPanel korisniciOpcije;
    private javax.swing.JPanel korisniciPanel;
    private javax.swing.JPanel ocitanjaDinamicki;
    private javax.swing.JMenu ocitanjaMenu;
    private javax.swing.JPanel ocitanjaOpcije;
    private javax.swing.JPanel ocitanjaPanel;
    private javax.swing.JPanel parametriDinamicki;
    private javax.swing.JMenu parametriMenu;
    private javax.swing.JPanel parametriOpcije;
    private javax.swing.JPanel parametriPanel;
    private javax.swing.JPanel potrosaciDinamicki;
    private javax.swing.JMenu potrosaciMenu;
    private javax.swing.JPanel potrosaciOpcije;
    private javax.swing.JPanel potrosaciPanel;
    private javax.swing.JPanel racuniDinamicki;
    private javax.swing.JMenu racuniMenu;
    private javax.swing.JPanel racuniOpcije;
    private javax.swing.JPanel racuniPanel;
    private javax.swing.JLayeredPane slojevi;
    // End of variables declaration//GEN-END:variables
}
