/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ba.etf.unsa.si.app.ui;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import ba.unsa.etf.si.app.entity.Ocitanja;
import ba.unsa.etf.si.app.entity.Potrosac;
import ba.unsa.etf.si.app.services.OcitanjaService;
import ba.unsa.etf.si.app.services.PotrosacService;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeEvent;

import javax.swing.JFormattedTextField;
import javax.swing.JTextField;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author Azra
 */
public class OcitanjaPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form OcitanjaPanel2
     */
    public OcitanjaPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jList1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mousePressed(MouseEvent e) {
        		try{
        		jFormattedTextField5.setText("");
        		try{
        			Integer.valueOf(jList1.getSelectedValue().toString());
        		}catch(Exception eks)
        		{
        			jFormattedTextField5.setText("Nema ocitanja!");
        			return;
        		}
            	int i = Integer.valueOf(jList1.getSelectedValue().toString());
            	OcitanjaService oS = new OcitanjaService();
                String[] x = jFormattedTextField4.getText().split("/");
                x[1]= x[1].replaceAll("\\s","");
                if(x[0].trim().length()==0 || x[0].trim().length()==1 || x[1].trim().length()==2 || x[1].trim().length()==3)
                {
                	jFormattedTextField5.setText("Nema ocitanja!");
                	return;
                }
                List<Ocitanja> o = oS.getId(i);
                Ocitanja novi = new Ocitanja();
                Boolean pomocna = false;

                int k = Integer.valueOf(x[0]);
                int j = Integer.valueOf(x[1]);
                for (Ocitanja tmp : o) 
                {
                	int a = tmp.getMjesec();
                	int b = tmp.getGodina();
                	
                	if(a==k && b==j)
                	{
                		novi=tmp;
                		pomocna=true;
                	}
                }
                if(pomocna==true){
            	jFormattedTextField5.setText(novi.getPotrosnja().toString());
                }
                else
                {
                	jFormattedTextField5.setText("Nema ocitanja!");
                }
              }
    	catch(Exception exp)
    	{
    		JOptionPane.showMessageDialog(null, exp.getMessage(),"Greska!",JOptionPane.ERROR_MESSAGE);
    	}
        	}
        });
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new JFormattedTextField();
        DefaultListModel model = new DefaultListModel();
        PotrosacService servicePotrosaca = new PotrosacService();
        OcitanjaService oS = new OcitanjaService();
        List<Potrosac> listPotrosaca = servicePotrosaca.dajSvePotrosace();
        jList1.setModel(model);
        for (Potrosac p : listPotrosaca) {         
        			if(p.getKategorija().equals("Pausalni"))
        			{
        				continue;
        			}
        			try{
                	if(oS.getId(p.getSifraVodomjera()).size()!=0)
                	{
                		if(p.getAktivnost()==true && p.getHidden()==false)
                		{
                		model.addElement(p.getSifraVodomjera());
                		}
                	}
                    	}
                    	catch(Exception e)
                    	{
                    		continue;
                    	}	
                
        		}
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jFormattedTextField4.addKeyListener(new KeyAdapter() {
        	@Override
        	public void keyReleased(KeyEvent arg0) {
        		try{
            		jFormattedTextField5.setText("");
            		try{
            			Integer.valueOf(jList1.getSelectedValue().toString());
            		}catch(Exception eks)
            		{
            			jFormattedTextField5.setText("Nema ocitanja!");
            			return;
            		}
                	int i = Integer.valueOf(jList1.getSelectedValue().toString());
                	OcitanjaService oS = new OcitanjaService();
                    String[] x = jFormattedTextField4.getText().split("/");
                    x[1]= x[1].replaceAll("\\s","");
                    if(x[0].trim().length()==0 || x[0].trim().length()==1 || x[1].trim().length()==2 || x[1].trim().length()==3)
                    {
                    	jFormattedTextField5.setText("Nema ocitanja!");
                    	return;
                    }
                    List<Ocitanja> o = oS.getId(i);
                    Ocitanja novi = new Ocitanja();
                    Boolean pomocna = false;

                    int k = Integer.valueOf(x[0]);
                    int j = Integer.valueOf(x[1]);
                    for (Ocitanja tmp : o) 
                    {
                    	int a = tmp.getMjesec();
                    	int b = tmp.getGodina();
                    	
                    	if(a==k && b==j && tmp.getAccess()==true)
                    	{
                    		novi=tmp;
                    		pomocna=true;
                    	}
                    }
                    if(pomocna==true){
                	jFormattedTextField5.setText(novi.getPotrosnja().toString());
                    }
                    else
                    {
                    	jFormattedTextField5.setText("Nema ocitanja!");
                    }
                  }
        	catch(Exception exp)
        	{
        		JOptionPane.showMessageDialog(null, exp.getMessage(),"Greska!",JOptionPane.ERROR_MESSAGE);
        	}
        	}
        });
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextField5 = new JTextField();  
        jButton1 = new javax.swing.JButton();
        jButton1.addMouseListener(new MouseAdapter() {
        	@Override
        	public void mouseReleased(MouseEvent arg0) {
        		
        		BtnIzmijeniOcitanjeActionPerformed(arg0);
        		
        	}
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Odabir vodomjera", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jScrollPane1.setViewportView(jList1);

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 102, 153));
        jLabel16.setText("po šifri ");

        jTextField7.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(0, 102, 153));
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtSifraVodomjeraPretragaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jTextField7)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 114, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(5, 5, 5)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Izmijeni očitanje", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 153));
        jLabel9.setText("Period (mm/yyyy)");

        jFormattedTextField4.setForeground(new java.awt.Color(0, 102, 153));
        try {
            jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/20##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField4.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 102, 153));
        jLabel12.setText("Stanje vodomjera");

        jFormattedTextField5.setForeground(new java.awt.Color(0, 102, 153));
        try {
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("IZMIJENI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        
    } 
        // </editor-fold>//GEN-END:initComponents
    
    private void BtnIzmijeniOcitanjeActionPerformed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSpasiNovoOcitanjeActionPerformed
        try{
        	if(jList1.isSelectionEmpty()==true)
        	{
        		throw new IllegalArgumentException("Niste izabrali vodomjer!");
        	}
        	else if(jFormattedTextField5.getText().trim().length()==0)
        	{
        		throw new IllegalArgumentException("Niste unijeli stanje vodomjera!");
        	}
        	try{
        		Double.valueOf(jFormattedTextField5.getText());
        	}
        	catch(Exception e)
        	{
        		throw new IllegalArgumentException("Pogresno stanje vodomjera, niste unijeli brojeve!");
        	}
        	try{
        		Integer.valueOf(jList1.getSelectedValue().toString());
        	}
        	catch(Exception novi)
        	{
        		throw new IllegalArgumentException("Niste selektovali ispravan vodomjer!");
        	}
            int sifraVodomjera = Integer.valueOf(jList1.getSelectedValue().toString());
            Double novoStanje = Double.valueOf(jFormattedTextField5.getText());
            OcitanjaService oS = new OcitanjaService();
            List<Ocitanja> o = oS.getId(sifraVodomjera);
            Ocitanja novi = new Ocitanja();
            String[] x = jFormattedTextField4.getText().split("/");
            x[1]= x[1].replaceAll("\\s","");
            if(x[0].trim().length()==0 || x[0].trim().length()==1 || x[1].trim().length()==2 || x[1].trim().length()==3)
            {
            	throw new IllegalArgumentException("Niste unijeli datum ispravno!");
            }
            if(Integer.valueOf(x[0])>12||Integer.valueOf(x[0])<0){
                throw new IllegalArgumentException("Nepostojeci mjesec");
            }
            
            int i = Integer.valueOf(x[0]);
            int j = Integer.valueOf(x[1]);
            
            
            for (Ocitanja tmp : o) 
            {
            	int a = tmp.getMjesec();
            	int b = tmp.getGodina();
            	
            	if(a==i && b==j && tmp.getAccess()==true)
            	{
            		novi=tmp;
            	}
            }
            novi.setPotrosnja(novoStanje);
            oS.modifyOcitanja(novi);
            
            jList1.removeAll();
            jFormattedTextField4.setText("");
            jTextField7.setText("");
            jFormattedTextField5.setText("");
            jList1.clearSelection();
            JOptionPane.showMessageDialog(null, "Uspjesno modifikovanje ocitanja za uneseni datum!");

        	}
        catch(Exception e){
           JOptionPane.showMessageDialog(null, e.getMessage(),"Greska!",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void TxtSifraVodomjeraPretragaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtSifraVodomjeraPretragaKeyReleased
    	DefaultListModel model = new DefaultListModel();
        jList1.removeAll();
        model.removeAllElements();
    try{
        PotrosacService servicePotrosaca = new PotrosacService();
        OcitanjaService oS = new OcitanjaService();
        List<Potrosac> listPotrosaca = servicePotrosaca.dajSvePotrosace();
        String sifra = jTextField7.getText();
        for (Potrosac listPotrosaca1 : listPotrosaca) {
            if(String.valueOf(listPotrosaca1.getSifraVodomjera()).contains(sifra)){
            	try{
            	if(oS.getId(listPotrosaca1.getSifraVodomjera()).size()!=0)
            	{
            		if(listPotrosaca1.getKategorija().equals("Pausalni"))
            		{
            			continue;
            		}
            		if(listPotrosaca1.getAktivnost()==true || listPotrosaca1.getHidden()==false)
            		{
                    model.addElement(listPotrosaca1.getSifraVodomjera());
            		}
            	}
            	}
            	catch(Exception e)
            	{
            		continue;
            	}
            }
        }
        jList1.setModel(model);
        
    }
    catch(Exception e){
        JOptionPane.showMessageDialog(null, e.getMessage(),"Greska!",JOptionPane.ERROR_MESSAGE);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private JTextField jFormattedTextField5;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private JFormattedTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
