/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ba.etf.unsa.si.app.ui;

import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import ba.unsa.etf.si.app.entity.Racuni;
import ba.unsa.etf.si.app.services.ObracunService;
import static com.sun.org.apache.xerces.internal.util.XMLChar.trim;
import javax.swing.JOptionPane;

/**
 *
 * @author Azra
 */
public class RacuniPregled extends javax.swing.JFrame {

    DatumUplate datum;
    /**
     * Creates new form RacuniPregled
     */
    transient private List<Racuni> racuni;
    public RacuniPregled() {
    	  initComponents();
          //boja pozadine
          Container container = this.getContentPane();
          container.setBackground(Color.white); 
    }
Date datumKreiranja;
int sifraRacuna;
String ime;
String prezime;
String sifraVodomjera;
Boolean nemaDatuma;
    public RacuniPregled(Date datumKreiranja1,int sifraRacuna1,
    		String ime1,String prezime1,String sifraVodomjera1,Boolean nemaDatuma1) {
    	  initComponents();
          datumKreiranja = datumKreiranja1;
          sifraRacuna = sifraRacuna1;
          ime=ime1;
          prezime=prezime1;
          sifraVodomjera=sifraVodomjera1;
          nemaDatuma=nemaDatuma1;
          update();
    }
	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        status = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 153));
        jButton1.setText("UPLATI");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Rezultati pretrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jTable1.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 102, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Ime", "Prezime", "Šifra računa", "Šifra vodomjera", "Period", "Utrošak m3", "Iznos", "Iznos sa PDV", "Iznos PVN", "Ukupan iznos", "Datum uplate"
            }
        ));
        jTable1.setInheritsPopupMenu(true);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 153));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                .addContainerGap())
        );

        status.setFont(new java.awt.Font("SansSerif", 1, 11)); // NOI18N
        status.setForeground(new java.awt.Color(255, 51, 51));
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setBorder(null);
        status.setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(734, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(status, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(79, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    	if(jTable1.getSelectedRow() == -1){
            status.setText("Izaberite račun");
        }
        else{
            status.setText("");
            if(racuni.isEmpty()){return;}
            String idString = String.valueOf(jTable1.getValueAt(jTable1.getSelectedRow(), 2));
            if("".equals(trim(idString))||idString==null){
                JOptionPane.showMessageDialog(null,"Niste izabrani ni jedan red");
                return;
            }
            int id = Integer.valueOf(idString);
            ObracunService s = new ObracunService();
            Racuni r = new Racuni();
            try{
                r = s.pretragaRacunaPoID(id);
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e.getMessage());
                return;
            }
            datum = new DatumUplate(r,this);
            datum.setVisible(true);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
public void update(){
//boja pozadine
          Container container = this.getContentPane();
          container.setBackground(Color.white); 
    	ObracunService servis = new ObracunService();
    	try{
    		racuni = servis.pretragaRacuna(datumKreiranja, sifraRacuna, ime, prezime, sifraVodomjera,nemaDatuma);
    	}
    	catch(Exception e){
    		JOptionPane.showMessageDialog(null, e.getMessage());
    	}
    	
    	
    	DefaultTableModel model1 = new DefaultTableModel(new Object[]{ "Ime", "Prezime", "Šifra računa", "Šifra vodomjera", "Period",
    			                            "Utrošak m3", "Iznos", "Iznos sa PDV", "PVN za koristenje voda", "PVN za zastitu voda", "Datum uplate"
                 },0);
    	for(Racuni racun:racuni){
    		Object[] red = new Object[11];
    		red[0] = racun.getPotrosac().getIme();
    		red[1] = racun.getPotrosac().getPrezime();
    		red[2] = racun.getId();
    		red[3] = racun.getOcitanja().getSifraVodomjera();
                
                String output = "";
                
                if(racun.getOcitanja().getMjesec()==1){
                    output = "12/"+(racun.getOcitanja().getGodina()-1);
                }
                else{
                    output = (racun.getOcitanja().getMjesec()-1) + "/" + racun.getOcitanja().getGodina();
                }
    		red[4] = output;
    		red[5] = racun.getPotrosnjaZaKoristenjeVoda();
    		red[6] = racun.getUkupnaCijena();
    		red[7] = racun.getUkupnaCijenaSaPdv();
    		red[8] = racun.getPvnZaKoristenjeVoda();
    		red[9] = racun.getPvnZaZastituVoda();
    		red[10] = racun.getDatumUplate();
    		
    		model1.addRow(red);
    	}
    	try{
            jTable1.setModel(model1);
	}
    
    catch(Exception e){
    	JOptionPane.showMessageDialog(null, e.getMessage());
    }

}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RacuniPregled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RacuniPregled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RacuniPregled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RacuniPregled.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RacuniPregled().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
